### ISSUE TITLE
pluralize doesn't work in French

### ISSUE THREAD

**Issue by redalastor** [NoRedInk/elm-string-extra#6]
French follows a different rule than English for pluralizing, everything in the -2 to 2 range (excluding boundary) is singular and everything else is plural.

Here's that as code, feel free to take it.

```
frenchPluralize : String -> String -> number -> String
frenchPluralize singular plural count =
    if count > -2 && count < 2 then
        (toString count) ++ " " ++ singular
    else
        (toString count) ++ " " ++ plural
```

**Comment by et** [comment]
From looking at this package, I don't think it respects (for lack of a better term) any language other than English.

**Comment by redalastor** [comment]
I'm wondering if the proper wouldn't be simply to take a Int -> Bool
function that decides if it's plural or not.

Le jeu. 29 sept. 2016 11:04, Eric Thomas notifications@github.com a
écrit :

**Comment by et** [comment]
I would suggest looking into something more [i18n friendly](http://www.gizra.com/content/elm-i18n-type-safety/).

**Comment by rtfeldman** [comment]
Thank you for raising this! This is a great point, but I think expanding the scope of the library to include non-English languages would get out of control pretty quickly.

I think we're going to stick to English on this one. 🙂
