### ISSUE TITLE
v0.18 compatibility

### ISSUE THREAD

**Issue by chadoh** [NoRedInk/elm-string-extra#7]
Going through [the lesson on Egghead that uses this package](https://egghead.io/lessons/elm-discover-new-packages-using-the-elm-package-index), but I have elm 0.18.0 installed. I can't currently use this package with 0.18.

Probably easy to add support for this, right? Something that an Elm newb like me might be able to manage?

**Comment by avh4** [comment]
Hello, you should switch to using http://package.elm-lang.org/packages/elm-community/string-extra/latest instead of NoRedInk/elm-string-extra
